# Generated by Django 4.2.6 on 2023-11-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_owner_alter_blog_image_alter_blog_source_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
