# Generated by Django 4.2.6 on 2023-11-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], default=0, max_length=200),
            preserve_default=False,
        ),
    ]
